# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amazon_ups.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61mazon_ups.proto\"8\n\x03\x45rr\x12\x0b\n\x03\x65rr\x18\x01 \x02(\t\x12\x14\n\x0coriginseqnum\x18\x02 \x02(\x03\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"\xb9\x01\n\x0c\x41OrderATruck\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x1a\n\x12warehouselocationx\x18\x02 \x02(\x05\x12\x1a\n\x12warehouselocationy\x18\x03 \x02(\x05\x12\x13\n\x0bwarehouseid\x18\x04 \x02(\x05\x12\x14\n\x0c\x64\x65stinationx\x18\x05 \x02(\x05\x12\x14\n\x0c\x64\x65stinationy\x18\x06 \x02(\x05\x12\r\n\x05upsid\x18\x07 \x01(\t\x12\x0e\n\x06seqnum\x18\x08 \x02(\x03\"2\n\rAStartDeliver\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"m\n\tAUCommand\x12\x1f\n\x07\x64\x65liver\x18\x01 \x03(\x0b\x32\x0e.AStartDeliver\x12\x1c\n\x05order\x18\x02 \x03(\x0b\x32\r.AOrderATruck\x12\x0c\n\x04\x61\x63ks\x18\x03 \x03(\x03\x12\x13\n\x05\x65rror\x18\x04 \x03(\x0b\x32\x04.Err\"B\n\x0cUTruckArrive\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x0f\n\x07truckid\x18\x02 \x02(\x05\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"/\n\nUDelivered\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"m\n\tUACommand\x12\x1d\n\x06\x61rrive\x18\x01 \x03(\x0b\x32\r.UTruckArrive\x12\x1e\n\tdelivered\x18\x02 \x03(\x0b\x32\x0b.UDelivered\x12\x0c\n\x04\x61\x63ks\x18\x03 \x03(\x03\x12\x13\n\x05\x65rror\x18\x04 \x03(\x0b\x32\x04.Err')



_ERR = DESCRIPTOR.message_types_by_name['Err']
_AORDERATRUCK = DESCRIPTOR.message_types_by_name['AOrderATruck']
_ASTARTDELIVER = DESCRIPTOR.message_types_by_name['AStartDeliver']
_AUCOMMAND = DESCRIPTOR.message_types_by_name['AUCommand']
_UTRUCKARRIVE = DESCRIPTOR.message_types_by_name['UTruckArrive']
_UDELIVERED = DESCRIPTOR.message_types_by_name['UDelivered']
_UACOMMAND = DESCRIPTOR.message_types_by_name['UACommand']
Err = _reflection.GeneratedProtocolMessageType('Err', (_message.Message,), {
  'DESCRIPTOR' : _ERR,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:Err)
  })
_sym_db.RegisterMessage(Err)

AOrderATruck = _reflection.GeneratedProtocolMessageType('AOrderATruck', (_message.Message,), {
  'DESCRIPTOR' : _AORDERATRUCK,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AOrderATruck)
  })
_sym_db.RegisterMessage(AOrderATruck)

AStartDeliver = _reflection.GeneratedProtocolMessageType('AStartDeliver', (_message.Message,), {
  'DESCRIPTOR' : _ASTARTDELIVER,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AStartDeliver)
  })
_sym_db.RegisterMessage(AStartDeliver)

AUCommand = _reflection.GeneratedProtocolMessageType('AUCommand', (_message.Message,), {
  'DESCRIPTOR' : _AUCOMMAND,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AUCommand)
  })
_sym_db.RegisterMessage(AUCommand)

UTruckArrive = _reflection.GeneratedProtocolMessageType('UTruckArrive', (_message.Message,), {
  'DESCRIPTOR' : _UTRUCKARRIVE,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UTruckArrive)
  })
_sym_db.RegisterMessage(UTruckArrive)

UDelivered = _reflection.GeneratedProtocolMessageType('UDelivered', (_message.Message,), {
  'DESCRIPTOR' : _UDELIVERED,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UDelivered)
  })
_sym_db.RegisterMessage(UDelivered)

UACommand = _reflection.GeneratedProtocolMessageType('UACommand', (_message.Message,), {
  'DESCRIPTOR' : _UACOMMAND,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UACommand)
  })
_sym_db.RegisterMessage(UACommand)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ERR._serialized_start=20
  _ERR._serialized_end=76
  _AORDERATRUCK._serialized_start=79
  _AORDERATRUCK._serialized_end=264
  _ASTARTDELIVER._serialized_start=266
  _ASTARTDELIVER._serialized_end=316
  _AUCOMMAND._serialized_start=318
  _AUCOMMAND._serialized_end=427
  _UTRUCKARRIVE._serialized_start=429
  _UTRUCKARRIVE._serialized_end=495
  _UDELIVERED._serialized_start=497
  _UDELIVERED._serialized_end=544
  _UACOMMAND._serialized_start=546
  _UACOMMAND._serialized_end=655
# @@protoc_insertion_point(module_scope)
